version: '3'

services:

  # Server
  server:
    build:
      context: ./server
    environment:
      - NODE_ENV=development
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
      
  # Client
  client:
    build:
      context: ./client
    expose:
      - "3000"
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules